# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imageUrl',
            new_name='imagePath',
        ),
    ]
