# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-13 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20191012_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['imageName']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location_name']},
        ),
    ]
